# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SimpleloginCli < Formula
  desc "SimpleLogin CLI — manage email aliases from the terminal"
  homepage "https://github.com/mexcool/simplelogin-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.4.0/simplelogin-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "be88d7b80206ed9a1b81afa86608f371d42e9f8fbf84a928d1f63f4a7a1de261"

      define_method(:install) do
        bin.install "sl"
        bin.install "simplelogin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.4.0/simplelogin-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "dbd69213767294e8d1b81619691aa869e9ff144c9df7a5c2917f968bd1784959"

      define_method(:install) do
        bin.install "sl"
        bin.install "simplelogin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.4.0/simplelogin-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "31a88ad566ede9575190238f1c882424a5acd380e5a1b40b8b4560fe85ae7b42"
      define_method(:install) do
        bin.install "sl"
        bin.install "simplelogin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.4.0/simplelogin-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "9a386d563eb89700cd13e0186d833379444164ec33cc3709183217c274931810"
      define_method(:install) do
        bin.install "sl"
        bin.install "simplelogin"
      end
    end
  end

  test do
    system "#{bin}/sl", "--version"
    system "#{bin}/simplelogin", "--version"
  end
end
