# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sl < Formula
  desc "SimpleLogin CLI — manage email aliases from the terminal"
  homepage "https://github.com/mexcool/simplelogin-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.1.0/simplelogin-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "7b28f3fd3e3d4b3b5f182fd094afc4eab2482e492c08d867ecb1a8e272f6180f"

      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.1.0/simplelogin-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "f7f15c9ead88e3733270cc9bc96baa2de4c94c3dbe127d531ac8021d912472f7"

      define_method(:install) do
        bin.install "sl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.1.0/simplelogin-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "dd3362b983169542da12584d9eb43ac4c48bc24160bccdc9d66ad9469cff803c"
      define_method(:install) do
        bin.install "sl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mexcool/simplelogin-cli/releases/download/v0.1.0/simplelogin-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "4e32866d08e01e6db8da3dbbdbcff68ecb49fd7f055aa6033e773aba8c905f99"
      define_method(:install) do
        bin.install "sl"
      end
    end
  end

  test do
    system "#{bin}/sl", "--version"
  end
end
